
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Provaiders from './Provaiders'
import { Navbar, Sidebar } from '@/components/ui'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'App jira',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provaiders>
          <Navbar/>
          <Sidebar/>

           {children}
        </Provaiders>
      
      </body>
    </html>
  )
}
